#
# These flags represent the build-time configuration of openssl for
# android
#
# They were pruned from the "Makefile" generated by running
# "./Configure linux-generic32 no-idea no-bf no-cast no-seed no-md2 -DL_ENDIAN" in the openssl distribution directory
#
